#!/bin/bash
set -euo pipefail

# CD to the directly this file is actually in
cd "$(dirname "$(realpath --logical "$0")")"

downloads="$(pwd)"/downloads
files="$(pwd)"/files
buildroot="$(pwd)"/buildroot
src="$buildroot"/src
stages="$(pwd)"/stages

crystal_stages="01"

export PATH="$buildroot/bin:$PATH"
export PKG_CONFIG_PATH="$buildroot/lib/pkgconfig"
export LD_LIBRARY_PATH="$buildroot/lib"
export GEM_HOME="$buildroot"/lib/ruby/gems/1.9.1

test -d "$downloads" || (echo "downloads directory doesn't exist" && exit 1)

echo "==> Checking files"

(
    cd "$downloads"

    sha256sum -c "$files"/openssl-1.0.2q.tar.gz.sha256
    sha256sum -c "$files"/ruby-1.9.3-p551.tar.gz.sha256
    sha256sum -c "$files"/llvm-3.3.src.tar.gz.sha256

    cd "$downloads"/gems

    sha256sum -c "$files"/gems.sha256
)

mkdir -p "$src" "$stages"

echo "==> Installing OpenSSL"
test -d "$src"/openssl-1.0.2q || (
    cd "$src"

    tar xzf "$downloads"/openssl-1.0.2q.tar.gz

    cd openssl-1.0.2q

    ./config --prefix="$buildroot" shared
    make "-j$(nproc --all)"
    make install
)


echo "==> Installing Ruby"
test -d "$src"/ruby-1.9.3-p551 || (
    cd "$src"

    tar xzf "$downloads"/ruby-1.9.3-p551.tar.gz

    cd ruby-1.9.3-p551

    autoconf
    ./configure --prefix="$buildroot" --enable-shared --disable-rpath
    make "-j$(nproc --all)"
    make install
)

echo "==> Installing LLVM 3.3"
test -d "$src"/llvm-3.3.src || (
    cd "$src"

    rm -Rf llvm-3.3.src
    tar xzf "$downloads"/llvm-3.3.src.tar.gz

    cd llvm-3.3.src

    CC=gcc CXX=g++ ./configure --prefix="$buildroot" --enable-shared --enable-assertions --with-python="$(command -v python2)"
    make "-j$(nproc --all)"
    make install
    ln -sf "$buildroot"/bin/llvm-config "$buildroot"/bin/llvm-config-3.3
)

echo "==> Installing Gems"

test -d "$src"/ruby-llvm || (
    rm -Rf "$src"/ruby-llvm
    git clone -q "$downloads"/gems/ruby-llvm.git "$src"/ruby-llvm

    cd "$src"/ruby-llvm

    git checkout aaadfe83a3f99b550f5f1b0756b1784db73e0c37
    gem build ruby-llvm.gemspec
)

test -d "$src"/ruby-prof || (
    rm -Rf "$src"/ruby-prof
    git clone -q "$downloads"/gems/ruby-prof.git "$src"/ruby-prof

    cd "$src"/ruby-prof

    git checkout e1d1ba17e13f8ef5e24097034095ecc182d785e0
    gem build ruby-prof.gemspec
)

cd "$src"

test -f "$src"/gems-installed || (
    gem install --no-rdoc --no-ri "$downloads"/gems/bundler-1.17.1.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/mime-types-1.25.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/rest-client-1.6.7.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/tins-0.9.0.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/term-ansicolor-1.2.2.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/multi_json-1.8.0.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/thor-0.18.1.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/simplecov-html-0.7.1.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/simplecov-0.7.1.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/coveralls-0.7.0.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/diff-lcs-1.2.4.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/ffi-1.9.0.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/json-1.7.7.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/levenshtein-ffi-1.0.2.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/rake-0.9.6.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/rspec-core-2.14.5.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/rspec-expectations-2.14.2.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/rspec-mocks-2.14.3.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/rspec-2.14.1.gem
    gem install --no-rdoc --no-ri "$downloads"/gems/ruby-graphviz-1.0.9.gem
    gem install --no-rdoc --no-ri "$src"/ruby-llvm/ruby-llvm-3.3.0.alpha.gem
    gem install --no-rdoc --no-ri "$src"/ruby-prof/ruby-prof-0.13.0.gem

    touch "$src"/gems-installed
)

clone-crystal-at() {
    local ref="$1"

    rm -Rf "$src"/crystal
    git clone -q "$downloads"/crystal.git "$src"/crystal
    (cd "$src"/crystal; git checkout -q "$ref")
}


echo "==> Bootstrapping Crystal (01/$crystal_stages)"
test -f "$stages"/01-crystal || (
    cd "$src"

    clone-crystal-at 04964442a2de0268f63c492b22b17cb502724fc7

    cd crystal

    patch -p1 < "$files"/stage1.patch

    bin/crystal -stats bootstrap/crystal.cr
    mv crystal "$stages"/01-crystal
)

echo "==> Bootstrapping Crystal (02/$crystal_stages)"
test -f "$stages"/02-crystal || (
    cd "$src"

    clone-crystal-at bffda57eafff50a41e86618f7c2726803d31e42c

    cd crystal

    sed -i 's/`llvm-config --libs --ldflags`/LLVM-3.3/' src/compiler/crystal/llvm.cr

    "$stages"/01-crystal -stats -o "$stages"/02-crystal src/compiler/crystal.cr
)

echo "==> Bootstrapping Crystal (03/$crystal_stages)"
test -f "$stages"/03-crystal || (
    cd "$src"

    clone-crystal-at 6657d3c84c93ec0c886aa9262b2a33791e22285f

    cd crystal

    patch -p1 < "$files"/stage3.patch
    "$stages"/02-crystal -stats --llc '-relocation-model=pic' -o "$stages"/03-crystal src/compiler/crystal.cr
)

echo "==> Bootstrapping Crystal (04/$crystal_stages)"
test -f "$stages"/04-crystal || (
    cd "$src"

    clone-crystal-at 407e719ddb90d27e45a2e25e82f8a4653ae45beb

    cd crystal

    "$stages"/03-crystal -stats --llc '-relocation-model=pic' -o "$stages"/04-crystal src/compiler/crystal.cr
)

echo "==> Bootstrapping Crystal (05/$crystal_stages)"
test -f "$stages"/05-crystal || (
    cd "$src"

    clone-crystal-at 4d343928fda4d728294965af95febb38afd0d0ac

    cd crystal

    patch -p1 < "$files"/stage5.patch
    "$stages"/04-crystal -stats --llc '-relocation-model=pic' -o "$stages"/05-crystal src/compiler/crystal.cr
)

echo "==> Bootstrapping Crystal (06/$crystal_stages)"
test -f "$stages"/06-crystal || (
    cd "$src"

    clone-crystal-at 72f260e00bf343d179dd2a72b5f6e699f9030739

    cd crystal

    "$stages"/05-crystal -stats --llc '-relocation-model=pic' -o "$stages"/06-crystal src/compiler/crystal.cr
)

echo "==> Bootstrapping Crystal (07/$crystal_stages)"
test -f "$stages"/07-crystal || (
    cd "$src"

    clone-crystal-at 90d7aad39c500fcbced6d5fba7f63098a0d24918

    cd crystal

    "$stages"/06-crystal -stats --llc '-relocation-model=pic' -o "$stages"/07-crystal src/compiler/crystal.cr
)

echo "==> Bootstrapping Crystal (08/$crystal_stages)"
test -f "$stages"/08-crystal || (
    cd "$src"

    clone-crystal-at 570be14b8bd422ebf68f2b4c65de8431d23014e1

    cd crystal

    "$stages"/07-crystal -stats --llc '-relocation-model=pic' -o "$stages"/08-crystal src/compiler/crystal.cr
)

echo "==> Bootstrapping Crystal (09/$crystal_stages)"
test -f "$stages"/09-crystal || (
    cd "$src"

    clone-crystal-at 6f084f00e416045a6a5de16e8a0637831e041f22

    cd crystal

    # addressof was renamed to pointerof in a sinle commit. This patch is just the compiler changes.
    patch -p1 < "$files"/stage9.patch
    "$stages"/08-crystal -stats --llc '-relocation-model=pic' -o "$stages"/09-crystal src/compiler/crystal.cr
)

echo "==> Bootstrapping Crystal (10/$crystal_stages)"
test -f "$stages"/10-crystal || (
    cd "$src"

    clone-crystal-at b2cdfe57ef177f3362a977ebd80fb3eed692b465

    cd crystal

    "$stages"/09-crystal -stats --llc '-relocation-model=pic' -o "$stages"/10-crystal src/compiler/crystal.cr
)

echo "==> Bootstrapping Crystal (11/$crystal_stages)"
test -f "$stages"/11-crystal || (
    cd "$src"

    clone-crystal-at 4ceda49393a5cd6063fcacc97acb6a5d19e5b0a2

    cd crystal

    patch -p1 < "$files"/stage11.patch
    "$stages"/10-crystal -stats --llc '-relocation-model=pic' -o "$stages"/11-crystal src/compiler/crystal.cr
)
